### ISSUE TITLE
Submitters not using reviews

### ISSUE THREAD

**Issue by sckott** [ropensci/onboarding-meta#21]
What do we do if submitters don't want to make changes that reviewers/editors suggest?  

I think we have to be firm about this.  If submitter gives good reasons for not making changes reviewers/editors suggest that's fine (and it should be item by item response too), but if there's a blanket statement that they just don't want to make the changes, I think we need to reject the submission. 

I think this scenario could arise from a submitter simply wanting to be under rOpenSci but not wanting to do the work.

**Comment by maelle** [comment]
TIL "blanket statement" 😸 

I agree but we first need to remind the submitter of the responsability they took when submitting, and of the reviewers' hard work. After this yes we should reject the submission. 😢 

Should we add something in the submission template e.g. "[] I confirm that I will respect and use the feedback provided by reviewers"? Or is too much given that it's rare to have someone not wanting to do the work? After all, "we hope you submit your package for review because you value the feedback."

**Comment by sckott** [comment]
(sorry about the jargon!)

Okay, yes, do remind them first (in the case in question that brought this up, I have reminded the submitter already)

I like that idea to have a check box - one could argue its so rare we don't need it though, what do others think?

**Comment by maelle** [comment]
Oh it's great to learn jargon!
I wonder if "regular" submitters would be shocked to have to check such a box.

**Comment by cboettig** [comment]
sorry to chime in.  I think the language should instead focus on making it clear that it is ultimately **editor**'s decision on whether or not to accept the package based on how the reviews are addressed, and not the reviewer's.  I don't think we want the impression that one must address everything in the review, however onerous, sometimes some discretion is needed there; but also having the decision ultimately fall to the editor shields the reviewers somewhat (i.e. if you don't like the decision, you should blame the editor and not the reviewers).

**Comment by maelle** [comment]
Really good point! 👌 (so obviously no reason to be sorry 😉 )

**Comment by sckott** [comment]
(please do chime in!) and good point @cboettig

**Comment by maelle** [comment]
I think the commit using Carl's wording in dev_guide clarified this, please re-open if not.
