### ISSUE TITLE
Suggest users add .github folder with files

### ISSUE THREAD

**Issue by sckott** [ropensci/onboarding-meta#22]
I propose we add in our instructions to approved submissions that if they don't have it yet, add a `.github` folder and use [our templates](https://github.com/ropensci/dotgithubfiles) for CONTRIBUTING, issue and PR templates

thoughts?

**Comment by karthik** [comment]
I like the idea, but if we do that, we should also clean up the text a little bit.  For e.g. instead of just "Please contribute!

We love collaboration."

Perhaps it could say a bit more about what types of contributions are welcome (doc updates, minor fixes, new features) and how to make them (not technical details, but general rules). 

The forking rules seem too verbose and also very specific to a particular style of working. These could also be made more general. The last 3 sentences for contributing are headings instead of sentences. 

But overall, with some clean up, I agree that we should recommend that people add them.

**Comment by maelle** [comment]
We should also encourage `reprex` use in CONTRIBUTING.md with a link to the corresponding comm call.

**Comment by maelle** [comment]
Closing in favor of #13
