### ISSUE TITLE
Best practices for CI for packaging guide

### ISSUE THREAD

**Issue by sckott** [ropensci/onboarding-meta#28]
e.g. and i'm not saying i am right, just examples

- run Travis on each of oldrel, release, and devel
- only run codecov on release
- if your pkg has compiled code, run on osx as well
- attempt to minimize travis check time as we can only have so many concurrent checks on travis

others?

**Comment by maelle** [comment]
This? https://github.com/ropenscilabs/tic

**Comment by sckott** [comment]
haven't looked at it yet. are you suggesting just to use it?

**Comment by karthik** [comment]
tic can do all of those things. We plan to finalize the documentation and write more examples for a March release. Will definitely write some custom recipes for onboarding, so this would be a good place to collect it.

We can act on release very easily because we can see tags. There are other ideas that I have that haven't been articulated. I need to do that more.  Examples of other things we can do:

- automatically build pkgdown docs
- automatically update tutorials on the ropensci website on new release, and email the maintainer if there are issues.
- I have meetings with various folks to resurrect a RTD collaboration. If that comes along, we can push docs to there as well. 

Maybe folks should list other recipes we need.

**Comment by maelle** [comment]
What is RTD?

**Comment by karthik** [comment]
Read the docs

________________________________

**Comment by karthik** [comment]
Sorry, I wasn’t asking you to read the docs. Just mentioning the service: https://readthedocs.org

It’s not used in the R community but should be.

**Comment by maelle** [comment]
😂 no worries I understood the 1st message right away but I like the irony.

**Comment by karthik** [comment]
Related to my earlier comment, we could also (automatically) CNAME the docs folder (which auto generates pkgdown docs) to <package>.ropensci.org 

So people would have a canonical place to look for our package docs. Just a thought.

**Comment by maelle** [comment]
Reg. "automatically build pkgdown docs" I'm not sure I 100% understood how it'd work. Would one .gitignore docs/ / just not have them locally?

**Comment by maelle** [comment]
In the meantime I understood what `tic` allows and use it for building the guide :joy: 

There's a CI chapter now in the guide, will soon have everything mentioned here (it just lacks Travis check time minimizing, and well `tic` stuff).

**Comment by maelle** [comment]
All tips from this thread are now in dev_guide, further discussion and suggestions in that repo, thanks.
