### ISSUE TITLE
Form based submission?

### ISSUE THREAD

**Issue by maelle** [ropensci/onboarding-meta#29]
Cf [this comment](https://github.com/ropensci/onboarding/pull/196#issuecomment-364648469) from @noamross (and I think an older suggestion from Karthik?)

# Plus sides

Easier for authors than filling the looong template

We get data that's easier to analyse from the template 😀

# Downsides

The authors don't have their submission as plain text that they could put under version control. I had thought of maybe an helper function to submit from R like `devtools::release` with custom checks and questions and the template filled _before_ calling the function (unlike `propose` in [`ro`](https://github.com/ropensci/ro)) in a .md like one does with cran-comments.md

**Comment by maelle** [comment]
Parts of the template could be filled automatically by a helper function 🤔

**Comment by karthik** [comment]
# 
Hi Maëlle! Yes this has definitely been one my early list of improvements for onboarding. It seemed clunky to ask authors to paste descriptions inside code blocks and most of what we’re asking could be automated and standardized. 

My vision back then was to have a simple form that asked for some basic info:
Begin with the repository URL - This could be used to automatically query the authors names, email, the full description file, the License, CRAN status etc. For a more advanced version, a bash (or other script) also runs good practice and reports test coverage/diagnostics to the issue as the first comment (within seconds of posting the issue itself).

This process could also be a `onboarding R package`. Just like `devtools::release()`, a author could release their package to onboarding review with a few questions instead of using a web form (and no reason both can’t exist)

Requests for publishing in JOSS (and more recently MEE) could be noted in the form (and we can give JOSS editors, myself and Arfon) a quick dashboard so we can accept quickly.

An API call from the form submission could template the issue and also enter the appropriate information into the databases. 

Another issue that’s been bothering me (I may have made a note of this earlier) is also the order in which we request the information on the current template.  To me, the first thing I want to see is the repo URL. That is buried half way down. It needs to be up top.

Also, we should standardize the submission template to be clean key value pairs so that allows us to automatically parse the issues at a later time (although Maëlle’s current work could make that unnecessary)

**Comment by noamross** [comment]
# Other Plus sides

-  Long form could be made shorter with form logic (e.g., if you select that you plan to submit to JOSS, it shows the JOSS-related checkmarks
-  Certain checkmarks would have to be checked to submit
-  Would make automated checking easier (as information would come in standardized)

# Cons
-  I think one reason this keeps being discussed and rarely implemented is that it's easy for the task to expand to include a whole suite of automation features.  We should scope a minimum unit of work that allows for further expansion later.

# Mitigating factors
- If we use `ro::propose()` or (`submit()`?) It could (a) take as an input a YAML/JSON/TOML template that would would validate and then be used to submit, or (b) ask questions interactively and generate this file before submission.

# Misc
- Not sure where to put this, but we should probably be suggesting that authors run `goodpractice::gp()` themselves before submitting.

**Comment by maelle** [comment]
closing in favor of @noamross ' duplicate #51 where I think all key elements from above are mentioned.
