### ISSUE TITLE
Answer the blind review question

### ISSUE THREAD

**Issue by maelle** [ropensci/onboarding-meta#33]
https://github.com/ropensci/onboarding/issues/101#issuecomment-287622571

**Comment by sckott** [comment]
i haven't thought deeply about this, but my gut reaction is that open review is a better option, but perhaps we can look at some of the literature on this.

**Comment by karthik** [comment]
I veer towards open review. Why? Because for the case of software, it's much harder to be subjective than a regular manuscript review. I can nitpick to no end and crap on someone's idea. But here I can state with evidence that using `sapply` within a package is bad. 
Sure, some design considerations might be subjective, but those are the topics being discussed.

On a JOSS thread there is a very poor submission that I have been beating down and it's slowly getting in shape. My comments are harsh but also fair and the open aspect isn't affecting my ability to do so.

Perhaps we could open up the option for someone to post comments anonymously via the editor and the editor could make sure that they are fair and no ad hominem attacks.

**Comment by karthik** [comment]
Double blind is just hard if not impossible in this case

**Comment by maelle** [comment]
Should I try to digest your answers into a blurb "Why our reviews are open" in the bookdown?

**Comment by noamross** [comment]
We did write a version of this in the [NumFOCUS blog post](https://ropensci.org/blog/2017/09/01/nf-softwarereview/): 

> The exchange is also open and public. Authors, reviewers, and editors all know each other’s identities. The broader community can view or even participate in the conversation as it happens. This provides an incentive to be thorough and provide non-adversarial, constructive reviews. Both authors and reviewers report that they enjoy and learn more from this open and direct exchange. It also has the benefit of building community. Participants have the opportunity to meaningfully network with new peers, and new collaborations have emerged via ideas spawned during the review process.
>
> We are aware that open systems can have drawbacks. For instance, in traditional academic review, double-blind peer review can increase representation of female authors, suggesting bias in non-blind reviews. It is also possible reviewers are less critical in open review. However, we posit that the openness of the review conversation provides a check on review quality and bias; it’s harder to inject unsupported or subjective comments in public and without the cover of anonymity. Ultimately, we believe the ability of authors and reviewers to have direct but public communication improves quality and fairness.
